name: e_commers
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
 sdk: '>=2.12.0 <3.0.0'

dependencies:
  animate_do: ^2.0.0
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  kommunicate_flutter: ^1.3.1
  intl:
  
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_rating_bar: ^4.0.0
  flutter_secure_storage: ^5.0.2
  flutter_svg: ^1.0.0
  form_field_validator: ^1.1.0
  google_fonts: ^2.1.0
  http: ^0.13.4
  image_picker: ^0.8.4+4
  permission_handler: ^8.3.0
  shimmer: ^2.0.0
  stripe_payment: ^1.1.1
  timeago: ^3.1.0
  analyzer: '1.5.0'
  geolocator: ^8.2.0
  geocoding: ^2.0.4
  google_maps_flutter: ^2.1.3
  socket_io_client: ^1.0.2
  url_launcher: ^5.2.5
  firebase_messaging: ^11.2.14
  flutter_local_notifications: ^9.4.0
  font_awesome_flutter: ^10.1.0
  android_intent_plus: ^3.1.1
  polyline_do: ^0.1.0
  firebase_core: ^1.13.1
  fl_chart: ^0.50.6
  json_annotation: ^4.5.0
  select_form_field: ^2.2.0
  


dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icon/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
